### ISSUE TITLE
订阅B站动态时偶尔会有一直重复发同一段消息的情况。

### ISSUE THREAD

**Issue by Gilgaladly** [Sora233/bilidynamicpush#2]
消息推送的完之后一直在重复发一段消息，不重启不行= =也没有报错。

**Comment by Sora233** [comment]
能发一下日志看看吗

**Comment by Gilgaladly** [comment]
对比过日志，跟正常的时候发的时候是一样的。基本没有区别= =更多的日志的话hoshino也没有打印，暂时还不知道怎么办。

**Comment by Sora233** [comment]
描述一下具体情况，是只有同一条动态一直发吗，频率大概怎么样的

**Comment by Gilgaladly** [comment]
应该是默认的2分钟检测一次，然后一直发同一条动态。

**Comment by Sora233** [comment]
同一条动态每两分钟会发一次，重启之后别的动态也可能出现这个情况，是这样吗

**Comment by Gilgaladly** [comment]
是这样的。间隔大概几天会触发这种情况。

**Comment by Gilgaladly** [comment]
有时候是主播开播，有时候是转发动态，几个类型都出现过。

**Comment by Zoe-Wh1t3zZ** [comment]
![image](https://user-images.githubusercontent.com/94744908/154211732-4a3ed49c-e888-4f8a-84b7-797a7629fdaa.png)
