### ISSUE TITLE
直播推送好像寄了

### ISSUE THREAD

**Issue by chenchenriver** [Sora233/bilidynamicpush#4]
![ca](https://user-images.githubusercontent.com/93070768/139581848-8fe43cbe-86e8-478b-8c9e-23a5834921f1.png)
群友用这个的也出这个问题了，大佬救救孩子吧，没你的插件用我要死了了

**Comment by Sora233** [comment]
我会看一下的

**Comment by Sora233** [comment]
@xia0ti @chenchenriver 已更新，请用新版本

**Comment by xia0ti** [comment]
> @xia0ti @chenchenriver 已更新，请用新版本

非常感谢！！
